blueprint:
  name: Hive TRV Compensation
  description: Use external sensor for TRV current temperature
  domain: automation
  input:
    trv:
      name: TRV
      description: Select TRV
      selector:
        entity:
          domain: climate
    room:
      name: Room Temperature Sensor
      description: Select room Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
  
variables:
  var_trv: !input trv
  var_room: !input room
  trv_name: '{{ state_attr(var_trv, ''friendly_name'') }}'
  room_temp: '{{ states(var_room)|float }}'
  room_trv_temp: '{{ state_attr(var_trv, ''external_measured_room_sensor'')|float }}'
  room_trv_new_temp: '{{ ((states(var_room)|float)*100)|round(0) }}'
  
trigger:
  - platform: time_pattern
    minutes: "/31"
condition:
  - condition: template
    value_template: '{{ room_trv_new_temp != room_trv_temp }}'
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/{{trv_name}}/set/external_measured_room_sensor
      payload: '{{room_trv_new_temp}}'
mode: single
