blueprint:
  name: Tuya TRV Compensation
  description: Use room temperature to calibrate TRV
  domain: automation
  input:
    trv:
      name: TRV
      description: Select TRV
      selector:
        entity:
          domain: climate
    room:
      name: Room Temperature Sensor
      description: Select room Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
  
variables:
  var_trv: !input trv
  var_room: !input room
  trv_name: '{{ state_attr(var_trv, ''friendly_name'') }}'
  room_temp: '{{ states(var_room)|float(0) }}'
  room_trv_temp: '{{ state_attr(var_trv, ''local_temperature'')|float(0) }}'
  room_trv_calib: '{{ state_attr(var_trv, ''local_temperature_calibration'')|float(0) }}'
  room_trv_nocalib: '{{ (room_trv_temp - room_trv_calib)|float(0) }}'
  room_trv_newcalib: '{{ ((room_temp - room_trv_nocalib)|float(0))|round(1, "half") }}'

trigger:
  - platform: time_pattern
    minutes: "/2"
condition:
  - condition: template
    value_template: '{{ room_trv_newcalib != room_trv_calib }}'
  - condition: template
    value_template: '{{ room_trv_newcalib >= -15 }}'
  - condition: template
    value_template: '{{ room_trv_newcalib <= 15 }}'
action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/{{trv_name}}/set/local_temperature_calibration
      payload: '{{room_trv_newcalib}}'
mode: single
